import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { adminClient } from "@/lib/supabase";

const layout: Record<string,{sheet:string;headers:string[];select:string;row:(x:Record<string,any>)=>unknown[]}> = {
  visits:{sheet:"DAILY_LORRY_MOVEMENT",headers:["Visit ID","Date","Driver ID","Driver Name","Company","Lorry Registration","Vehicle Type","Security Guard","Security Registration Time","Company Time In","Loading Area In","Loading Area Out","Company Time Out","Loading Duration","Total Site Duration","Final Status"],select:"*,drivers(driver_code,full_name),companies(name),lorries(registration_number,vehicle_type),security_guards(full_name)",row:x=>[x.visit_code,x.visit_date,x.drivers?.driver_code||x.driver_id,x.drivers?.full_name,x.companies?.name,x.lorries?.registration_number,x.lorries?.vehicle_type,x.security_guards?.full_name,x.security_registered_at,x.company_time_in,x.loading_area_in,x.loading_area_out,x.company_time_out,x.loading_duration_seconds,x.total_duration_seconds,x.status]},
  drivers:{sheet:"DRIVERS",headers:["Driver ID","Driver Name","Phone","Company","Licence","Lorry Registration","Vehicle Type","Status","QR ID","Created Date"],select:"*,companies(name),lorries(registration_number,vehicle_type)",row:x=>[x.driver_code||x.id,x.full_name,x.phone,x.companies?.name,x.licence_number,x.lorries?.[0]?.registration_number,x.lorries?.[0]?.vehicle_type,x.active?"ACTIVE":"INACTIVE",x.qr_token,x.created_at]},
  companies:{sheet:"COMPANIES",headers:["Company ID","Company Name","Contact Person","Phone","Email","Status"],select:"*",row:x=>[x.company_code||x.id,x.name,x.contact_person,x.phone,x.email,x.active?"ACTIVE":"INACTIVE"]},
  lorries:{sheet:"LORRIES",headers:["Lorry ID","Registration Number","Company","Vehicle Type","Assigned Driver","Status"],select:"*,companies(name),drivers(full_name)",row:x=>[x.lorry_code||x.id,x.registration_number,x.companies?.name,x.vehicle_type,x.drivers?.full_name,x.active?"ACTIVE":"INACTIVE"]},
  security_attendance:{sheet:"SECURITY_ATTENDANCE",headers:["Attendance ID","Date","Guard ID","Guard Name","Shift","Site","Time In","Time Out","Hours Worked","Status"],select:"*,security_guards(guard_code,full_name)",row:x=>[x.id,x.date,x.security_guards?.guard_code||x.guard_id,x.security_guards?.full_name,x.shift,x.site,x.time_in,x.time_out,x.time_out?Math.round((new Date(x.time_out).getTime()-new Date(x.time_in).getTime())/360000)/10:null,x.status]},
  geofence_events:{sheet:"GEOFENCE_EVENTS",headers:["Event ID","Visit ID","Lorry","Driver","Event Type","Latitude","Longitude","Timestamp","Accuracy","Device ID"],select:"*,visits(visit_code,lorries(registration_number),drivers(full_name))",row:x=>[x.id,x.visits?.visit_code,x.visits?.lorries?.registration_number,x.visits?.drivers?.full_name,x.event_type,x.latitude,x.longitude,x.occurred_at,x.accuracy,x.device_id]}
};
function key() { const value=process.env.MICROSOFT_TOKEN_ENCRYPTION_KEY; if(!value) throw new Error("MICROSOFT_TOKEN_ENCRYPTION_KEY is missing"); const bytes=Buffer.from(value,"base64"); if(bytes.length!==32) throw new Error("Microsoft token encryption key must be 32 bytes, base64 encoded"); return bytes; }
export function encrypt(value:string) { const iv=randomBytes(12); const cipher=createCipheriv("aes-256-gcm",key(),iv); const ciphertext=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]); return Buffer.concat([iv,cipher.getAuthTag(),ciphertext]).toString("base64"); }
function decrypt(value:string) { const bytes=Buffer.from(value,"base64"); const decipher=createDecipheriv("aes-256-gcm",key(),bytes.subarray(0,12)); decipher.setAuthTag(bytes.subarray(12,28)); return Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()]).toString("utf8"); }
export function microsoftConfig() { const {MICROSOFT_CLIENT_ID:clientId,MICROSOFT_CLIENT_SECRET:clientSecret,MICROSOFT_TENANT_ID:tenantId,MICROSOFT_DRIVE_ID:driveId,MICROSOFT_WORKBOOK_ID:workbookId,APP_URL:appUrl}=process.env; if(!clientId||!clientSecret||!tenantId||!driveId||!workbookId||!appUrl) throw new Error("Microsoft Graph environment variables are incomplete"); return {clientId,clientSecret,tenantId,driveId,workbookId,appUrl}; }
export async function exchangeCode(code:string) { const c=microsoftConfig(); const body=new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,grant_type:"authorization_code",code,redirect_uri:`${c.appUrl}/api/microsoft/callback`,scope:"offline_access Files.ReadWrite User.Read"}); const response=await fetch(`https://login.microsoftonline.com/${c.tenantId}/oauth2/v2.0/token`,{method:"POST",body}); const data=await response.json(); if(!response.ok||!data.refresh_token) throw new Error(data.error_description||"Microsoft authorization failed"); return String(data.refresh_token); }
async function accessToken() { const c=microsoftConfig(); const db=adminClient(); const {data,error}=await db.from("microsoft_connections").select("encrypted_refresh_token").eq("id",1).single(); if(error||!data) throw new Error("Microsoft Excel is not connected"); const body=new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,grant_type:"refresh_token",refresh_token:decrypt(data.encrypted_refresh_token),scope:"offline_access Files.ReadWrite User.Read"}); const response=await fetch(`https://login.microsoftonline.com/${c.tenantId}/oauth2/v2.0/token`,{method:"POST",body}); const token=await response.json(); if(!response.ok||!token.access_token) throw new Error(token.error_description||"Microsoft token refresh failed"); if(token.refresh_token) await db.from("microsoft_connections").update({encrypted_refresh_token:encrypt(token.refresh_token),updated_at:new Date().toISOString()}).eq("id",1); return String(token.access_token); }
async function graph(token:string,path:string,method="GET",body?:unknown) { const response=await fetch(`https://graph.microsoft.com/v1.0${path}`,{method,headers:{Authorization:`Bearer ${token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined}); const text=await response.text(); const data=text?JSON.parse(text):{}; if(!response.ok) throw new Error(`Graph ${response.status}: ${data.error?.message||text}`); return data; }
function column(index:number) { let out=""; for(let n=index+1;n;n=Math.floor((n-1)/26)) out=String.fromCharCode(65+(n-1)%26)+out; return out; }
function cell(value:unknown) { if(value===null||value===undefined) return ""; if(typeof value==="number"||typeof value==="boolean") return value; const text=String(value); return /^[=+\-@]/.test(text)?`'${text}`:text; }
export async function syncOne(entityType:string,entityId:string) {
  const spec=layout[entityType]; if(!spec) throw new Error(`Unsupported Excel entity: ${entityType}`);
  const db=adminClient(); const {data:record,error}=await db.from(entityType).select(spec.select).eq("id",entityId).single(); if(error||!record) throw error||new Error("Record not found");
  const token=await accessToken(); const c=microsoftConfig(); const root=`/drives/${encodeURIComponent(c.driveId)}/items/${encodeURIComponent(c.workbookId)}/workbook`;
  const sheets=await graph(token,`${root}/worksheets`); if(!(sheets.value as {name:string}[]).some(s=>s.name===spec.sheet)) await graph(token,`${root}/worksheets/add`,"POST",{name:spec.sheet});
  const sheet=`${root}/worksheets/${encodeURIComponent(spec.sheet)}`;
  const range=await graph(token,`${sheet}/usedRange(valuesOnly=true)`); const values:Array<Array<unknown>>=range.values||[];
  if(!values.length||String(values[0]?.[0]||"")!==spec.headers[0]) await graph(token,`${sheet}/range(address='A1:${column(spec.headers.length-1)}1')`,"PATCH",{values:[spec.headers]});
  const row=spec.row(record as Record<string,any>).map(cell); const key=String(row[0]);
  let rowNumber=values.findIndex((r,i)=>i>0&&String(r[0])===key)+1;
  if(rowNumber===0) rowNumber=Math.max(2,values.length+1);
  await graph(token,`${sheet}/range(address='A${rowNumber}:${column(row.length-1)}${rowNumber}')`,"PATCH",{values:[row]});
  await db.from("excel_row_map").upsert({entity_type:entityType,entity_id:entityId,worksheet:spec.sheet,row_number:rowNumber},{onConflict:"entity_type,entity_id"});
}
export async function processSyncQueue(limit=10) { const db=adminClient(); const now=new Date().toISOString(); await db.from("excel_sync_queue").update({sync_status:"failed",last_sync_error:"Worker timed out"}).eq("sync_status","processing").lt("next_attempt_at",now);
  const {data:items,error}=await db.from("excel_sync_queue").select("*").in("sync_status",["pending","failed"]).lte("next_attempt_at",now).order("created_at").limit(limit); if(error) throw error;
  let synced=0,failed=0;
  for(const item of items||[]) { const attempts=item.sync_attempts+1; const {data:claimed}=await db.from("excel_sync_queue").update({sync_status:"processing",sync_attempts:attempts,next_attempt_at:new Date(Date.now()+10*60_000).toISOString()}).eq("id",item.id).in("sync_status",["pending","failed"]).select("id").maybeSingle(); if(!claimed) continue;
    try { await syncOne(item.entity_type,item.entity_id); await db.from("excel_sync_queue").update({sync_status:"synced",last_sync_error:null,last_sync_time:new Date().toISOString()}).eq("id",item.id); synced++; }
    catch(error) { await db.from("excel_sync_queue").update({sync_status:"failed",last_sync_error:String(error).slice(0,1000),next_attempt_at:new Date(Date.now()+Math.min(60,2**Math.min(attempts,6))*60_000).toISOString()}).eq("id",item.id); failed++; }
  }
  return {synced,failed};
}
